GET http://localhost:5000/zainals

###

GET http://localhost:5000/auth

###

POST  http://localhost:5000/auth/register
Content-Type: application/json

{
    "name" : "Informatika 2023",
    "address" : "Malang City",
    "email" : "informatika23@gmail.com",
    "phone" : "62812",
    "password" : "Infokom23"
}

###

POST  http://localhost:5000/auth/register
Content-Type: application/json

{
    "name" : "Zainal Saputra",
    "address" : "Surabaya",
    "email" : "zainals@bnsp.in",
    "phone" : "62811",
    "password" : "Bnsp11",
    "role": "admin"
}

###

POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "email" : "informatika23@gmail.com",
    "password" : "Infokom23"
}

###

POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "email" : "zainals@bnsp.in",
    "password" : "Bnsp11"
}

###

GET  http://localhost:5000/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmZjgwZTcyLTU0ZjktNGE0Zi05YjlmLTgzZDhiMjdhMzZmNCIsIm5hbWUiOiJaYWluYWwgU2FwdXRyYSIsImVtYWlsIjoiemFpbmFsc0BibnNwLmluIiwiaWF0IjoxNzIxOTc3Njg2LCJleHAiOjE3MjE5Nzc3MDZ9.DkaNMFlCBW1X1A1qj0jC7824fNlQTdZxM2yZUzDWPE0

###

GET  http://localhost:5000/auth/token

###

DELETE   http://localhost:5000/auth/logout