GET http://localhost:5000/zainals

###

GET http://localhost:5000/books

###

POST  http://localhost:5000/books
Content-Type: application/json

{
    "title" : "Informatika 2023",
    "author" : "Malang City",
    "description" : "informatika23@gmail.com",
    "image" : "62812"
}

###

DELETE   http://localhost:5000/auth/logout