GET http://localhost:5000/zainals

###

GET http://localhost:5000/books/rental

###

POST  http://localhost:5000/books/rental/7428fe78-2adf-4919-acbf-bb914d0c4d8e
Content-Type: application/json

{
    
}

###

DELETE   http://localhost:5000/auth/logout