GET http://localhost:5000/zainals

###

GET http://localhost:5000/books/rental

###

POST  http://localhost:5000/books/rental/66a613bb-f9e3-4990-bb77-3d2529ed49d1
Content-Type: application/json

{
    
}

###

PUT  http://localhost:5000/books/rental/439139d5-14a1-4293-bf71-07a891effd77
Content-Type: application/json

{
    
}

###

DELETE   http://localhost:5000/auth/logout