GET http://localhost:5000/zainals

###

GET http://localhost:5000/books/rental

###

POST  http://localhost:5000/books/rental/eb38293d-ffa1-4c24-a4c9-5dda07ba6f95
Content-Type: application/json

{
    
}

###

PUT  http://localhost:5000/books/rental/23c4c9d4-eb8f-496f-b3c6-a7d7ee1035ad
Content-Type: application/json

{
    
}

###

DELETE   http://localhost:5000/auth/logout